name: Build, Lint, and Test

on:
  push:
    branches:
      - main  # Запускать только для push'ей в ветку main

jobs:
  build-lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    
    - name: Install Dependencies
      run: npm install
      
    - name: Lint TypeScript
      run: npm run lint  # Предполагается, что в вашем проекте есть скрипт "lint" для запуска ESLint
      
    - name: Build TypeScript
      run: npm run build
      
    - name: Run Tests
      run: npm test
    - name: Run tests with coverage
      run: make test-coverage
    - name: Debug List contents of coverage directory
      run: ls -R coverage
    - name: Save coverage report
      run: |
        mkdir -p ~/cc-test-reporter
        cp coverage/coverage-final.json ~/cc-test-reporter/coverage-final.json
    
    - name: Upload coverage
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ~/cc-test-reporter/test-reporter
        chmod +x ~/cc-test-reporter/test-reporter
        ~/cc-test-reporter/test-reporter format-coverage -t lcov ~/cc-test-reporter/lcov.info
        ~/cc-test-reporter/test-reporter upload-coverage
